[package]
name = "discord-fank"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
shuttle-service = { version = "0.5.2", features = ["bot-serenity", "sqlx-postgres", "secrets"] }
log = "0.4.17"
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres"] }
